### ISSUE TITLE
Problem with submitToGallery($pic['id'],$data)

### ISSUE THREAD

**Issue by canetti2** [j0k3r/php-imgur-api-client#47]
Hi,
everything works fine but unfortunatly I get an error when using this function: 

**$client->api('gallery')->submitToGallery($pic['id'],$data);**

Error:
<b>Fatal error</b>:  Uncaught TypeError: Imgur\HttpClient\HttpClient::parseResponse(): Return value must be of type array, bool returned in /www/htdocs/w019a155/mysite/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/HttpClient/HttpClient.php:116
Stack trace:
#0 /www/htdocs/w019a155/mysite/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/Api/AbstractApi.php(58): Imgur\HttpClient\HttpClient-&gt;parseResponse(Object(GuzzleHttp\Psr7\Response))
#1 /www/htdocs/w019a155/mysite/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/Api/Gallery.php(231): Imgur\Api\AbstractApi-&gt;post('gallery/1tGNf19', Array)
#2 /www/htdocs/w019a155/mysite/imgur/authenticationCallBack.php(50): Imgur\Api\Gallery-&gt;submitToGallery('1tGNf19', Array)
#3 {main}
  thrown in <b>/www/htdocs/w019a155/mysite/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/HttpClient/HttpClient.php</b> on line <b>116</b><br />

Do you have an explanation?

**Comment by j0k3r** [comment]
Maybe because the `data` attribute of the response is not always an array but can be null, boolean or integer and the library doesn't seems handle it properly: https://api.imgur.com/models/basic

Try to dump the `$responseBody` variable [here](https://github.com/j0k3r/php-imgur-api-client/blob/6da5dfab1b8922b223cb3b1031dd4da834112055/lib/Imgur/HttpClient/HttpClient.php#L113) to see what you get
